### ISSUE TITLE
docker documentation wrong/missing

### ISSUE THREAD

**Issue by xenoterracide** [theory/tap-parser-sourcehandler-pgtap#36]
first, it'd be nice if the docs mentioned the docker distribution, it's not at the top of the dockerhub list (I'll remove mine), the dockerhub documentation is wrong, the link leads to a 404

```
docker pull itheory/pg_prove
curl -L https://git.io/fpgAk -o pg_prove && chmod +x pg_prove
./pg_prove --help
```

also the docker documentation should probably mention the environment variables... I wonder if it would be better to have a sample docker-compose file documented instead of this pg_prove script, since you can run `docker-compose up` and if it's a container that just exits it will exit when it's done.

maybe something like this

```yaml
version: '3.7'
services:
  pg_prove:
    image: itheory/pg_prove
    command: --ext .sql --recurse
    volumes:
      - ./:/repo
      - ${PGSERVICEFILE:-./pg_service.conf}:/root/.pg_service.conf
      - ${PGPASSFILE:-./pgpass}:/root/.pgpass
    environment:
      PGSERVICE: ${PGSERVICE:-localhost}
    network_mode: host
```

one last thing, why is the script mounting $HOME? this seems... strange, and maybe a bad idea in certain CI environments
